create extension if not exists btree_gist;
drop schema if exists temporal cascade;
drop schema if exists nontemporal cascade;
drop schema if exists ids cascade;
create schema temporal;
create schema nontemporal;
create schema ids;

create table ids.clients (
  id integer generated by default as identity primary key
);
create table temporal.clients (
  id integer generated by default as identity,
  valid_at daterange,
  name text,
  constraint pk_clients primary key (id, valid_at without overlaps),
  constraint fk_clients_id foreign key (id) references ids.clients (id)
);
create table nontemporal.invoices (
  id integer generated by default as identity primary key,
  client_id integer not null references ids.clients (id),
  number integer not null
);

with new_ids as (
  insert into ids.clients DEFAULT VALUES returning id
)
insert into temporal.clients (id, valid_at, name)
  select id, daterange(current_date, null), 'Nadir'
  from new_ids;
  
insert into nontemporal.invoices (client_id, number)
  select max(id), 1001 from ids.clients;

select * from temporal.clients;
select * from nontemporal.invoices;

-- But now the sequence on temporal.clients is wrong because we didn't use it.
alter table temporal.clients alter column id set generated by default restart with 2;
 
-- WITH TRIGGERS:

/*                                                                                                 
 * Generate an ID for temporal.clients in temporal.single_clients                                  
 * so that non-temporal tables can have a foreign key reference to it.                             
 *                                                                                                 
 * Note this executes *before* temporal.clients own id column gets filled in by the GENERATED expression.                                                                                              * So if the is NULL, get an id from single_clients.                                               
 * Otherwise use the given id.                                                                     
 * (It's probably in single_clients already, but maybe not.)                                       
 */                                                                                                
CREATE OR REPLACE FUNCTION trg_generate_temporal_client_id()                                       
RETURNS trigger                                                                                    
LANGUAGE plpgsql                                                                                   
AS                                                                                                 
$$                                                                                                 
BEGIN                                                                                              
  IF NEW.id IS NULL THEN                                                                           
    NEW.id := nextval(pg_get_serial_sequence('temporal.clients', 'id'));                           
  END IF;                                                                                          
  INSERT INTO ids.clients (id) VALUES (NEW.id)                                         
    ON CONFLICT DO NOTHING;                                                                        
  RETURN NEW;                                                                                      
END;                                                                                               $$;

CREATE TRIGGER generate_temporal_client_id                                                         
  BEFORE INSERT ON temporal.clients                                                                
  FOR EACH ROW                                                                                     
  EXECUTE FUNCTION trg_generate_temporal_client_id();

-- test it:

insert into temporal.clients (id, valid_at, name)
  select id, daterange(current_date, null), name
  from (values
    (null, 'Acme'),
    (5, 'Mid')
	) x(id, name);
  
insert into nontemporal.invoices (client_id, number)
  select max(id), 1001 from ids.clients where id < 5;
insert into nontemporal.invoices (client_id, number)
  values (5, 1001);

select * from temporal.clients;
select * from nontemporal.invoices;
 
