create extension if not exists btree_gist;
drop schema if exists temporal cascade;

create schema temporal;

/* work_categories */
CREATE TABLE temporal.work_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  valid_at daterange,
  client_id integer not null,
  name text not null,
  rate float not null,
  CONSTRAINT work_categories_pk PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)
);
CREATE VIEW work_categories AS
  SELECT id, client_id, name, rate
  FROM temporal.work_categories
  WHERE valid_at @> current_date;

INSERT INTO temporal.work_categories (valid_at, client_id, name, rate) VALUES
  ('[2000-01-01,2020-01-01)', 5, 'Coding', 150),
  ('[2020-01-01,)', 5, 'Coding', 165);
SELECT * FROM temporal.work_categories ORDER BY id, valid_at;
SELECT * FROM work_categories ORDER BY id;

/* work_categories: INSERT */
CREATE OR REPLACE FUNCTION insert_work_categories_view()
RETURNS trigger
LANGUAGE plpgsql
AS
$$
BEGIN
  INSERT INTO temporal.work_categories
    (client_id, name, rate, valid_at) VALUES
    (NEW.client_id,  NEW.name, NEW.rate, daterange(current_date, null))
    RETURNING id INTO NEW.id;
  RETURN NEW;
END;
$$;
CREATE TRIGGER insert_work_categories
  INSTEAD OF INSERT ON work_categories
  FOR EACH ROW
  EXECUTE FUNCTION insert_work_categories_view();

-- It's awesome that RETURNING works and gives us the ids generated by the base table!:
-- It only works if you RETURN NEW though.
\echo INSERT RETURNING:
INSERT INTO work_categories (client_id, name, rate) VALUES
  (6, 'Consulting', 250),
  (6, 'Managing', 300)
  RETURNING *;
SELECT * FROM temporal.work_categories ORDER BY id, valid_at;
SELECT * FROM work_categories ORDER BY id;

/* work_categories: UPDATE */
CREATE OR REPLACE FUNCTION update_work_categories_view()
RETURNS trigger
LANGUAGE plpgsql
AS
$$
BEGIN
  UPDATE temporal.work_categories
    FOR PORTION OF valid_at FROM current_date TO null
    SET client_id = NEW.client_id,
        name = NEW.name,
        rate = NEW.rate
    WHERE id = NEW.id;
  RETURN NEW;
END;
$$;
CREATE TRIGGER update_work_categories
  INSTEAD OF UPDATE ON work_categories
  FOR EACH ROW
  EXECUTE FUNCTION update_work_categories_view();

\echo UPDATE RETURNING:
UPDATE work_categories
  SET name = 'Development'
  WHERE name = 'Coding'
  RETURNING *
  ;
SELECT * FROM temporal.work_categories ORDER BY id, valid_at;
SELECT * FROM work_categories ORDER BY id;

/* work_categories: DELETE */
CREATE OR REPLACE FUNCTION delete_work_categories_view()
RETURNS trigger
LANGUAGE plpgsql
AS
$$
BEGIN
  DELETE FROM temporal.work_categories
    FOR PORTION OF valid_at FROM current_date TO null
    WHERE id = OLD.id;
  -- return OLD to get RETURNING:
  RETURN OLD;
END;
$$;
CREATE TRIGGER delete_work_categories
  INSTEAD OF DELETE ON work_categories
  FOR EACH ROW
  EXECUTE FUNCTION delete_work_categories_view();

\echo DELETE RETURNING:
DELETE FROM work_categories
  WHERE name = 'Managing'
  RETURNING *
  ;
SELECT * FROM temporal.work_categories ORDER BY id, valid_at;
SELECT * FROM work_categories ORDER BY id;
